// Code generated by "stringer -type=Stage"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Start-0]
	_ = x[Thrown-1]
	_ = x[Picked-2]
	_ = x[Invalid-3]
	_ = x[Stole-4]
	_ = x[Taken-5]
}

const _Stage_name = "StartThrownPickedInvalidStoleTaken"

var _Stage_index = [...]uint8{0, 5, 11, 17, 24, 29, 34}

func (i Stage) String() string {
	if i < 0 || i >= Stage(len(_Stage_index)-1) {
		return "Stage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Stage_name[_Stage_index[i]:_Stage_index[i+1]]
}
