###  Get Server state
GET http://{{host}}:{{port}}/
Accept: application/json

### Create Game
POST http://{{host}}:{{port}}/game
Content-Type: application/json

{
  "Players": ["Dick", "Lucy", "Janneke"]
}
> {%
    client.test("Got a gamekey back", function() {
        client.assert(response.body.Key != null)
        client.assert(response.body.Key.length > 0)
    });
    client.global.set("gamekey", response.body.Key);
    client.log("Saved 'gamekey': " + response.body.Key);
%}

### Get Active Games
GET http://{{host}}:{{port}}/games

### Get Game info
GET http://{{host}}:{{port}}/game/{{gamekey}}/info

### Get current turn info
GET http://{{host}}:{{port}}/game/{{gamekey}}/turn

### Throw for the current turn
POST http://{{host}}:{{port}}/game/{{gamekey}}/throw

### Pick a number
POST http://{{host}}:{{port}}/game/{{gamekey}}/pick
Content-Type: application/json

{
  "Pick": 4
}

### Start a new turn for the next player
POST http://{{host}}:{{port}}/game/{{gamekey}}/nextplayer
Content-Type: application/json
